rails_practice/kelsey_blog/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/about_me' => 'welcome#about_me'
  get 'posts/drafts' => 'posts#draft'
  get 'posts/search' => 'posts#index'
  resources :posts 

   root 'welcome#index'

     

end

rails_practice/kelsey_blog/app/models/post.rb
class Post < ActiveRecord::Base
  scope :draft, -> { where(draft_status: true) }
  scope :is_published, -> { where(draft_status: false) }
  scope :most_recent, -> { order('published desc').limit(10).is_published }
  scope :search, -> (q) { where("subject LIKE ? OR body LIKE ?", "%#{q}%", "%#{q}%").most_recent }
  validates :subject, presence: true
  validates :body, presence: true
  
end

rails_practice/kelsey_blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    if params[:q]
      @posts = Post.search(params[:q])
    else
      @posts = Post.most_recent
    end
    # @posts = Post.most_recent.where(nil)
    # @posts = Post.search(params[:search]) if params[:search].present?
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def draft
    @drafts = Post.draft
  end

   def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:subject, :body, :published, :draft_status)
    end


end

rails_practice/kelsey_blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about_me
  end
  
end

rails_practice/kelsey_blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails_practice/kelsey_blog/app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1>
        <%= link_to 'Kelsey\'s Blog', root_path %>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider hide-for-small"></li>
      <li>
        <%= link_to 'Github', 'https://github.com/kwoodard22' %>
      </li>

      <li class="divider hide-for-small"></li>
      <li>
        <%= link_to 'Twitter', 'https://twitter.com/KelseyMWoodard' %>
      </li>

      <li class="divider hide-for-small"></li>
      <li>
        <%= link_to 'About Me', '/welcome/about_me' %>
      </li>
    </ul>
  </section>
</nav>

rails_practice/kelsey_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kelsey's Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'layouts/header' %>

  <div id="main">
    <%= yield %>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>

rails_practice/kelsey_blog/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.date_select :published %>
  </div>
  <div class="field">
    <%= f.label :draft_status %><br>
    <%= f.check_box :draft_status %>
  </dvi>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_practice/kelsey_blog/app/views/posts/_search.html.erb
<%= form_tag("/posts/search", method: "get") do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

rails_practice/kelsey_blog/app/views/posts/draft.html.erb
<h1>Draft Posts</h1>

<ul>
  <% @drafts.each do |post| %>
    <li><%= link_to post.subject, post %>  (<%= post.published %>)</li>
  <% end %>
</ul>


________________________<br><br>
<strong><%= link_to 'BACK', posts_path %></strong> 

rails_practice/kelsey_blog/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

rails_practice/kelsey_blog/app/views/posts/index.html.erb
<div class="header">
  <h2>Kelsey's Blog</h2>

  <%= render 'search' %>
</div>
<ul class="posts">
  <% if @posts.empty? %>
    <li> No posts have been written </li>
  <% else %>
    <% @posts.each do |post| %>
     <li class="post"><%= link_to post.subject, post %>  (<%= post.published %>)</li>
  <% end %>
  <% end %>
</ul>

________________________<br><br>
<i class="fi-pencil"></i>
<strong><%= link_to 'ADD NEW POST', new_post_path %></strong> | <strong><%= link_to 'DRAFTS', posts_drafts_path %></strong>

rails_practice/kelsey_blog/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

rails_practice/kelsey_blog/app/views/posts/show.html.erb
<h1><%= @post.subject %></h1>
<br>
<p><%= @post.body %></p>
<br>
<p><strong>Published: </strong><%= @post.published %></p>

<tr>
  <td><%= link_to "Back", posts_path %> | </td>
  <td><%= link_to "Edit", edit_post_path %> | </td>
  <td><%= link_to "Destroy", @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

rails_practice/kelsey_blog/app/views/welcome/about_me.html.erb
<h1>About Me:</h1>

rails_practice/kelsey_blog/app/views/welcome/index.html.erb
<h1>Welcome to Kelsey's Blog!</h1>

<div class="welcome">
  <p>This is a space where I write about stuff and recognize awesome things.</p>

  <strong><%= link_to 'VIEW POSTS', posts_path %></strong>  
</div>